# Generated by Django 6.0.1 on 2026-07-03 20:50

from django.db import migrations

def copy_address(apps, schema_editor):
    School = apps.get_model("school", "School")
    for school in School.objects.all():
        if school.address and not school.physical_address:
            school.physical_address = school.address
            school.save()

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_county_school_email_from_address_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_address),
    ]
