# Generated by Django 6.0.1 on 2026-06-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_assigned', to='staff.staff'),
        ),
    ]
