# Generated by Django 6.0.1 on 2026-06-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classroom_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='academic_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='classroom',
            name='curriculum',
            field=models.CharField(default='CBC', max_length=20),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='stream',
            field=models.CharField(default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
