# Generated by Django 6.0.1 on 2026-07-01 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classroom_academic_year_classroom_curriculum_and_more'),
        ('staff', '0002_staff_shif_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='curriculum',
            field=models.CharField(choices=[('CBC', 'CBC'), ('844', '8-4-4')], default='CBC', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subject',
            name='grading_system',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_core',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='learning_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='periods_per_week',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                ('period_number', models.IntegerField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('is_break', models.BooleanField(default=False)),
                ('break_name', models.CharField(blank=True, max_length=100, null=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.classroom')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'ordering': ['day', 'period_number'],
                'unique_together': {('class_room', 'day', 'period_number')},
            },
        ),
    ]
