# Generated by Django 6.0.1 on 2026-07-01 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subject_curriculum_subject_grade_levels_and_more'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('exam', 'Exam'), ('holiday', 'Holiday'), ('closure', 'Closure'), ('meeting', 'Meeting'), ('activity', 'Activity'), ('trip', 'Trip'), ('deadline', 'Deadline'), ('other', 'Other')], default='other', max_length=20)),
                ('scope', models.CharField(choices=[('school', 'School-wide'), ('grade', 'Grade Level'), ('class', 'Specific Class')], default='school', max_length=20)),
                ('grade_level', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('term', models.IntegerField()),
                ('year', models.IntegerField()),
                ('visible_to_parents', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_events', to='academics.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_term_events', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_events', to='exams.exam')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_term_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'title'],
            },
        ),
    ]
