# Generated by Django 6.0.1 on 2026-07-01 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('students', '0002_alter_student_options_remove_student_enrollment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='schoolmessage',
            name='channel',
            field=models.CharField(default='announcement', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolmessage',
            name='recipient_type',
            field=models.CharField(default='all_parents', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolmessage',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_messages', to='students.student'),
        ),
        migrations.AlterField(
            model_name='schoolmessage',
            name='scope',
            field=models.CharField(choices=[('school', 'All School'), ('grade', 'Grade Level'), ('class', 'Specific Class'), ('individual', 'Individual Student/Parent')], default='school', max_length=20),
        ),
        migrations.CreateModel(
            name='ParentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_by_staff', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.schoolmessage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_replies', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('school_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='messaging.schoolmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'school_message')},
            },
        ),
    ]
