# Generated by Django 6.0.1 on 2026-07-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_termevent'),
        ('fees', '0001_initial'),
        ('students', '0002_alter_student_options_remove_student_enrollment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeLevy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('trip', 'Trip'), ('uniform', 'Uniform'), ('activity', 'Activity'), ('other', 'Other')], default='other', max_length=20)),
                ('scope', models.CharField(choices=[('all', 'All Students'), ('class', 'Class'), ('grade', 'Grade'), ('individual', 'Individual')], default='all', max_length=20)),
                ('grade_level', models.CharField(blank=True, max_length=20)),
                ('student_ids', models.JSONField(blank=True, default=list)),
                ('academic_year', models.IntegerField(default=2026)),
                ('term', models.IntegerField(default=1)),
                ('due_date', models.DateField()),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('issued_by', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='LevyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('levy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.feelevy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levy_payments', to='students.student')),
            ],
            options={
                'unique_together': {('levy', 'student')},
            },
        ),
    ]
