# Generated by Django 6.0.1 on 2026-07-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feestructure_versioning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['-year', '-term', 'grade_level']},
        ),
    ]
