# Generated by Django 6.0.1 on 2026-07-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birth_cert_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='curriculum',
            field=models.CharField(choices=[('CBC', 'CBC'), ('844', '8-4-4')], default='CBC', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='nemis_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
