# Generated by Django 6.0.1 on 2026-07-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_date_user_first_name_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('headteacher', 'Head Teacher'), ('deputy', 'Deputy Principal'), ('hod', 'Head of Department'), ('class_teacher', 'Class Teacher'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('staff', 'Staff'), ('parent', 'Parent')], default='staff', max_length=20),
        ),
    ]
