# Generated by Django 6.0.1 on 2026-06-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='shif_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
