/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportCardsRouteImport } from './routes/report-cards'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as WebsiteRouteRouteImport } from './routes/_website/route'
import { Route as WebsiteIndexRouteImport } from './routes/_website/index'
import { Route as StudentsNewRouteImport } from './routes/students.new'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as StaffLeaveRouteImport } from './routes/staff.leave'
import { Route as StaffIdRouteImport } from './routes/staff.$id'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as ReportsNemisRouteImport } from './routes/reports.nemis'
import { Route as ReportsAuditRouteImport } from './routes/reports.audit'
import { Route as ReportsAcademicRouteImport } from './routes/reports.academic'
import { Route as FeesStructuresRouteImport } from './routes/fees.structures'
import { Route as FeesOutstandingRouteImport } from './routes/fees.outstanding'
import { Route as FeesCollectionRouteImport } from './routes/fees.collection'
import { Route as ExamsIdRouteImport } from './routes/exams.$id'
import { Route as ClassesIdRouteImport } from './routes/classes.$id'
import { Route as WebsiteTermsRouteImport } from './routes/_website/terms'
import { Route as WebsiteSchoolLifeRouteImport } from './routes/_website/school-life'
import { Route as WebsitePrivacyRouteImport } from './routes/_website/privacy'
import { Route as WebsiteParentsRouteImport } from './routes/_website/parents'
import { Route as WebsiteOurStaffRouteImport } from './routes/_website/our-staff'
import { Route as WebsiteNewsRouteImport } from './routes/_website/news'
import { Route as WebsiteGalleryRouteImport } from './routes/_website/gallery'
import { Route as WebsiteContactRouteImport } from './routes/_website/contact'
import { Route as WebsiteAdmissionsRouteImport } from './routes/_website/admissions'
import { Route as WebsiteAcademicsRouteImport } from './routes/_website/academics'
import { Route as WebsiteAboutRouteImport } from './routes/_website/about'
import { Route as WebsiteNewsSlugRouteImport } from './routes/_website/news.$slug'
import { Route as WebsiteAdmissionsApplyRouteImport } from './routes/_website/admissions.apply'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportCardsRoute = ReportCardsRouteImport.update({
  id: '/report-cards',
  path: '/report-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteRouteRoute = WebsiteRouteRouteImport.update({
  id: '/_website',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteIndexRoute = WebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)
const StaffLeaveRoute = StaffLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => StaffRoute,
} as any)
const StaffIdRoute = StaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const ReportsNemisRoute = ReportsNemisRouteImport.update({
  id: '/reports/nemis',
  path: '/reports/nemis',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAuditRoute = ReportsAuditRouteImport.update({
  id: '/reports/audit',
  path: '/reports/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAcademicRoute = ReportsAcademicRouteImport.update({
  id: '/reports/academic',
  path: '/reports/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesStructuresRoute = FeesStructuresRouteImport.update({
  id: '/fees/structures',
  path: '/fees/structures',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesOutstandingRoute = FeesOutstandingRouteImport.update({
  id: '/fees/outstanding',
  path: '/fees/outstanding',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesCollectionRoute = FeesCollectionRouteImport.update({
  id: '/fees/collection',
  path: '/fees/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIdRoute = ExamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExamsRoute,
} as any)
const ClassesIdRoute = ClassesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClassesRoute,
} as any)
const WebsiteTermsRoute = WebsiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsiteSchoolLifeRoute = WebsiteSchoolLifeRouteImport.update({
  id: '/school-life',
  path: '/school-life',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsitePrivacyRoute = WebsitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsiteParentsRoute = WebsiteParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsiteOurStaffRoute = WebsiteOurStaffRouteImport.update({
  id: '/our-staff',
  path: '/our-staff',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsiteNewsRoute = WebsiteNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsiteGalleryRoute = WebsiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsiteContactRoute = WebsiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsiteAdmissionsRoute = WebsiteAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsiteAcademicsRoute = WebsiteAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsiteAboutRoute = WebsiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsiteNewsSlugRoute = WebsiteNewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WebsiteNewsRoute,
} as any)
const WebsiteAdmissionsApplyRoute = WebsiteAdmissionsApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => WebsiteAdmissionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WebsiteIndexRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRouteWithChildren
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/portal': typeof PortalRoute
  '/report-cards': typeof ReportCardsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRoute
  '/timetable': typeof TimetableRoute
  '/about': typeof WebsiteAboutRoute
  '/academics': typeof WebsiteAcademicsRoute
  '/admissions': typeof WebsiteAdmissionsRouteWithChildren
  '/contact': typeof WebsiteContactRoute
  '/gallery': typeof WebsiteGalleryRoute
  '/news': typeof WebsiteNewsRouteWithChildren
  '/our-staff': typeof WebsiteOurStaffRoute
  '/parents': typeof WebsiteParentsRoute
  '/privacy': typeof WebsitePrivacyRoute
  '/school-life': typeof WebsiteSchoolLifeRoute
  '/terms': typeof WebsiteTermsRoute
  '/classes/$id': typeof ClassesIdRoute
  '/exams/$id': typeof ExamsIdRoute
  '/fees/collection': typeof FeesCollectionRoute
  '/fees/outstanding': typeof FeesOutstandingRoute
  '/fees/structures': typeof FeesStructuresRoute
  '/reports/academic': typeof ReportsAcademicRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/nemis': typeof ReportsNemisRoute
  '/settings/users': typeof SettingsUsersRoute
  '/staff/$id': typeof StaffIdRoute
  '/staff/leave': typeof StaffLeaveRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/new': typeof StudentsNewRoute
  '/admissions/apply': typeof WebsiteAdmissionsApplyRoute
  '/news/$slug': typeof WebsiteNewsSlugRoute
}
export interface FileRoutesByTo {
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRouteWithChildren
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/portal': typeof PortalRoute
  '/report-cards': typeof ReportCardsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRoute
  '/timetable': typeof TimetableRoute
  '/about': typeof WebsiteAboutRoute
  '/academics': typeof WebsiteAcademicsRoute
  '/admissions': typeof WebsiteAdmissionsRouteWithChildren
  '/contact': typeof WebsiteContactRoute
  '/gallery': typeof WebsiteGalleryRoute
  '/news': typeof WebsiteNewsRouteWithChildren
  '/our-staff': typeof WebsiteOurStaffRoute
  '/parents': typeof WebsiteParentsRoute
  '/privacy': typeof WebsitePrivacyRoute
  '/school-life': typeof WebsiteSchoolLifeRoute
  '/terms': typeof WebsiteTermsRoute
  '/classes/$id': typeof ClassesIdRoute
  '/exams/$id': typeof ExamsIdRoute
  '/fees/collection': typeof FeesCollectionRoute
  '/fees/outstanding': typeof FeesOutstandingRoute
  '/fees/structures': typeof FeesStructuresRoute
  '/reports/academic': typeof ReportsAcademicRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/nemis': typeof ReportsNemisRoute
  '/settings/users': typeof SettingsUsersRoute
  '/staff/$id': typeof StaffIdRoute
  '/staff/leave': typeof StaffLeaveRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/new': typeof StudentsNewRoute
  '/': typeof WebsiteIndexRoute
  '/admissions/apply': typeof WebsiteAdmissionsApplyRoute
  '/news/$slug': typeof WebsiteNewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_website': typeof WebsiteRouteRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRouteWithChildren
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/portal': typeof PortalRoute
  '/report-cards': typeof ReportCardsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRoute
  '/timetable': typeof TimetableRoute
  '/_website/about': typeof WebsiteAboutRoute
  '/_website/academics': typeof WebsiteAcademicsRoute
  '/_website/admissions': typeof WebsiteAdmissionsRouteWithChildren
  '/_website/contact': typeof WebsiteContactRoute
  '/_website/gallery': typeof WebsiteGalleryRoute
  '/_website/news': typeof WebsiteNewsRouteWithChildren
  '/_website/our-staff': typeof WebsiteOurStaffRoute
  '/_website/parents': typeof WebsiteParentsRoute
  '/_website/privacy': typeof WebsitePrivacyRoute
  '/_website/school-life': typeof WebsiteSchoolLifeRoute
  '/_website/terms': typeof WebsiteTermsRoute
  '/classes/$id': typeof ClassesIdRoute
  '/exams/$id': typeof ExamsIdRoute
  '/fees/collection': typeof FeesCollectionRoute
  '/fees/outstanding': typeof FeesOutstandingRoute
  '/fees/structures': typeof FeesStructuresRoute
  '/reports/academic': typeof ReportsAcademicRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/nemis': typeof ReportsNemisRoute
  '/settings/users': typeof SettingsUsersRoute
  '/staff/$id': typeof StaffIdRoute
  '/staff/leave': typeof StaffLeaveRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/new': typeof StudentsNewRoute
  '/_website/': typeof WebsiteIndexRoute
  '/_website/admissions/apply': typeof WebsiteAdmissionsApplyRoute
  '/_website/news/$slug': typeof WebsiteNewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/exams'
    | '/login'
    | '/payroll'
    | '/portal'
    | '/report-cards'
    | '/settings'
    | '/staff'
    | '/students'
    | '/subjects'
    | '/timetable'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/news'
    | '/our-staff'
    | '/parents'
    | '/privacy'
    | '/school-life'
    | '/terms'
    | '/classes/$id'
    | '/exams/$id'
    | '/fees/collection'
    | '/fees/outstanding'
    | '/fees/structures'
    | '/reports/academic'
    | '/reports/audit'
    | '/reports/nemis'
    | '/settings/users'
    | '/staff/$id'
    | '/staff/leave'
    | '/students/$id'
    | '/students/new'
    | '/admissions/apply'
    | '/news/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/exams'
    | '/login'
    | '/payroll'
    | '/portal'
    | '/report-cards'
    | '/settings'
    | '/staff'
    | '/students'
    | '/subjects'
    | '/timetable'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/news'
    | '/our-staff'
    | '/parents'
    | '/privacy'
    | '/school-life'
    | '/terms'
    | '/classes/$id'
    | '/exams/$id'
    | '/fees/collection'
    | '/fees/outstanding'
    | '/fees/structures'
    | '/reports/academic'
    | '/reports/audit'
    | '/reports/nemis'
    | '/settings/users'
    | '/staff/$id'
    | '/staff/leave'
    | '/students/$id'
    | '/students/new'
    | '/'
    | '/admissions/apply'
    | '/news/$slug'
  id:
    | '__root__'
    | '/_website'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/exams'
    | '/login'
    | '/payroll'
    | '/portal'
    | '/report-cards'
    | '/settings'
    | '/staff'
    | '/students'
    | '/subjects'
    | '/timetable'
    | '/_website/about'
    | '/_website/academics'
    | '/_website/admissions'
    | '/_website/contact'
    | '/_website/gallery'
    | '/_website/news'
    | '/_website/our-staff'
    | '/_website/parents'
    | '/_website/privacy'
    | '/_website/school-life'
    | '/_website/terms'
    | '/classes/$id'
    | '/exams/$id'
    | '/fees/collection'
    | '/fees/outstanding'
    | '/fees/structures'
    | '/reports/academic'
    | '/reports/audit'
    | '/reports/nemis'
    | '/settings/users'
    | '/staff/$id'
    | '/staff/leave'
    | '/students/$id'
    | '/students/new'
    | '/_website/'
    | '/_website/admissions/apply'
    | '/_website/news/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WebsiteRouteRoute: typeof WebsiteRouteRouteWithChildren
  AttendanceRoute: typeof AttendanceRoute
  ClassesRoute: typeof ClassesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExamsRoute: typeof ExamsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PayrollRoute: typeof PayrollRoute
  PortalRoute: typeof PortalRoute
  ReportCardsRoute: typeof ReportCardsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  StudentsRoute: typeof StudentsRouteWithChildren
  SubjectsRoute: typeof SubjectsRoute
  TimetableRoute: typeof TimetableRoute
  FeesCollectionRoute: typeof FeesCollectionRoute
  FeesOutstandingRoute: typeof FeesOutstandingRoute
  FeesStructuresRoute: typeof FeesStructuresRoute
  ReportsAcademicRoute: typeof ReportsAcademicRoute
  ReportsAuditRoute: typeof ReportsAuditRoute
  ReportsNemisRoute: typeof ReportsNemisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-cards': {
      id: '/report-cards'
      path: '/report-cards'
      fullPath: '/report-cards'
      preLoaderRoute: typeof ReportCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_website': {
      id: '/_website'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebsiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_website/': {
      id: '/_website/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebsiteIndexRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/students/new': {
      id: '/students/new'
      path: '/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/staff/leave': {
      id: '/staff/leave'
      path: '/leave'
      fullPath: '/staff/leave'
      preLoaderRoute: typeof StaffLeaveRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/$id': {
      id: '/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof StaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/reports/nemis': {
      id: '/reports/nemis'
      path: '/reports/nemis'
      fullPath: '/reports/nemis'
      preLoaderRoute: typeof ReportsNemisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/audit': {
      id: '/reports/audit'
      path: '/reports/audit'
      fullPath: '/reports/audit'
      preLoaderRoute: typeof ReportsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/academic': {
      id: '/reports/academic'
      path: '/reports/academic'
      fullPath: '/reports/academic'
      preLoaderRoute: typeof ReportsAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees/structures': {
      id: '/fees/structures'
      path: '/fees/structures'
      fullPath: '/fees/structures'
      preLoaderRoute: typeof FeesStructuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees/outstanding': {
      id: '/fees/outstanding'
      path: '/fees/outstanding'
      fullPath: '/fees/outstanding'
      preLoaderRoute: typeof FeesOutstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees/collection': {
      id: '/fees/collection'
      path: '/fees/collection'
      fullPath: '/fees/collection'
      preLoaderRoute: typeof FeesCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$id': {
      id: '/exams/$id'
      path: '/$id'
      fullPath: '/exams/$id'
      preLoaderRoute: typeof ExamsIdRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/classes/$id': {
      id: '/classes/$id'
      path: '/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof ClassesIdRouteImport
      parentRoute: typeof ClassesRoute
    }
    '/_website/terms': {
      id: '/_website/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof WebsiteTermsRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/school-life': {
      id: '/_website/school-life'
      path: '/school-life'
      fullPath: '/school-life'
      preLoaderRoute: typeof WebsiteSchoolLifeRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/privacy': {
      id: '/_website/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof WebsitePrivacyRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/parents': {
      id: '/_website/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof WebsiteParentsRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/our-staff': {
      id: '/_website/our-staff'
      path: '/our-staff'
      fullPath: '/our-staff'
      preLoaderRoute: typeof WebsiteOurStaffRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/news': {
      id: '/_website/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof WebsiteNewsRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/gallery': {
      id: '/_website/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof WebsiteGalleryRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/contact': {
      id: '/_website/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof WebsiteContactRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/admissions': {
      id: '/_website/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof WebsiteAdmissionsRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/academics': {
      id: '/_website/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof WebsiteAcademicsRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/about': {
      id: '/_website/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof WebsiteAboutRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/news/$slug': {
      id: '/_website/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof WebsiteNewsSlugRouteImport
      parentRoute: typeof WebsiteNewsRoute
    }
    '/_website/admissions/apply': {
      id: '/_website/admissions/apply'
      path: '/apply'
      fullPath: '/admissions/apply'
      preLoaderRoute: typeof WebsiteAdmissionsApplyRouteImport
      parentRoute: typeof WebsiteAdmissionsRoute
    }
  }
}

interface WebsiteAdmissionsRouteChildren {
  WebsiteAdmissionsApplyRoute: typeof WebsiteAdmissionsApplyRoute
}

const WebsiteAdmissionsRouteChildren: WebsiteAdmissionsRouteChildren = {
  WebsiteAdmissionsApplyRoute: WebsiteAdmissionsApplyRoute,
}

const WebsiteAdmissionsRouteWithChildren =
  WebsiteAdmissionsRoute._addFileChildren(WebsiteAdmissionsRouteChildren)

interface WebsiteNewsRouteChildren {
  WebsiteNewsSlugRoute: typeof WebsiteNewsSlugRoute
}

const WebsiteNewsRouteChildren: WebsiteNewsRouteChildren = {
  WebsiteNewsSlugRoute: WebsiteNewsSlugRoute,
}

const WebsiteNewsRouteWithChildren = WebsiteNewsRoute._addFileChildren(
  WebsiteNewsRouteChildren,
)

interface WebsiteRouteRouteChildren {
  WebsiteAboutRoute: typeof WebsiteAboutRoute
  WebsiteAcademicsRoute: typeof WebsiteAcademicsRoute
  WebsiteAdmissionsRoute: typeof WebsiteAdmissionsRouteWithChildren
  WebsiteContactRoute: typeof WebsiteContactRoute
  WebsiteGalleryRoute: typeof WebsiteGalleryRoute
  WebsiteNewsRoute: typeof WebsiteNewsRouteWithChildren
  WebsiteOurStaffRoute: typeof WebsiteOurStaffRoute
  WebsiteParentsRoute: typeof WebsiteParentsRoute
  WebsitePrivacyRoute: typeof WebsitePrivacyRoute
  WebsiteSchoolLifeRoute: typeof WebsiteSchoolLifeRoute
  WebsiteTermsRoute: typeof WebsiteTermsRoute
  WebsiteIndexRoute: typeof WebsiteIndexRoute
}

const WebsiteRouteRouteChildren: WebsiteRouteRouteChildren = {
  WebsiteAboutRoute: WebsiteAboutRoute,
  WebsiteAcademicsRoute: WebsiteAcademicsRoute,
  WebsiteAdmissionsRoute: WebsiteAdmissionsRouteWithChildren,
  WebsiteContactRoute: WebsiteContactRoute,
  WebsiteGalleryRoute: WebsiteGalleryRoute,
  WebsiteNewsRoute: WebsiteNewsRouteWithChildren,
  WebsiteOurStaffRoute: WebsiteOurStaffRoute,
  WebsiteParentsRoute: WebsiteParentsRoute,
  WebsitePrivacyRoute: WebsitePrivacyRoute,
  WebsiteSchoolLifeRoute: WebsiteSchoolLifeRoute,
  WebsiteTermsRoute: WebsiteTermsRoute,
  WebsiteIndexRoute: WebsiteIndexRoute,
}

const WebsiteRouteRouteWithChildren = WebsiteRouteRoute._addFileChildren(
  WebsiteRouteRouteChildren,
)

interface ClassesRouteChildren {
  ClassesIdRoute: typeof ClassesIdRoute
}

const ClassesRouteChildren: ClassesRouteChildren = {
  ClassesIdRoute: ClassesIdRoute,
}

const ClassesRouteWithChildren =
  ClassesRoute._addFileChildren(ClassesRouteChildren)

interface ExamsRouteChildren {
  ExamsIdRoute: typeof ExamsIdRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsIdRoute: ExamsIdRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

interface SettingsRouteChildren {
  SettingsUsersRoute: typeof SettingsUsersRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsUsersRoute: SettingsUsersRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StaffRouteChildren {
  StaffIdRoute: typeof StaffIdRoute
  StaffLeaveRoute: typeof StaffLeaveRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffIdRoute: StaffIdRoute,
  StaffLeaveRoute: StaffLeaveRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsNewRoute: typeof StudentsNewRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
  StudentsNewRoute: StudentsNewRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WebsiteRouteRoute: WebsiteRouteRouteWithChildren,
  AttendanceRoute: AttendanceRoute,
  ClassesRoute: ClassesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExamsRoute: ExamsRouteWithChildren,
  LoginRoute: LoginRoute,
  PayrollRoute: PayrollRoute,
  PortalRoute: PortalRoute,
  ReportCardsRoute: ReportCardsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  StudentsRoute: StudentsRouteWithChildren,
  SubjectsRoute: SubjectsRoute,
  TimetableRoute: TimetableRoute,
  FeesCollectionRoute: FeesCollectionRoute,
  FeesOutstandingRoute: FeesOutstandingRoute,
  FeesStructuresRoute: FeesStructuresRoute,
  ReportsAcademicRoute: ReportsAcademicRoute,
  ReportsAuditRoute: ReportsAuditRoute,
  ReportsNemisRoute: ReportsNemisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
