# Generated by Django 6.0.1 on 2026-07-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('staff', '0002_staff_shif_number'),
        ('students', '0002_alter_student_options_remove_student_enrollment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_comments', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_comments', to='students.student')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
